create table google_merchandising.hits (
	dataSource text null,
	fullVisitorId text null,
	hitNumber integer null,
	"hour" integer null,
	isEntrance boolean null,
	isExit boolean null,
	isInteraction boolean null,
	latencyTracking text null,
	"minute" integer null,
	promotion text null,
	referer text null,
	"time" integer null,
	"type" text null,
	visitId text null,
	appInfo_screenDepth integer null,
	appInfo_landingScreenName text null,
	appInfo_exitScreenName text null,
	appInfo_screenName text null,
	page_searchKeyword text null,
	page_pagePathLevel1 text null,
	page_hostname text null,
	page_pagePathLevel3 text null,
	page_pageTitle text null,
	page_searchCategory text null,
	page_pagePath text null,
	page_pagePathLevel2 text null,
	page_pagePathLevel4 text null,
	contentGroup_contentGroup3 text null,
	contentGroup_contentGroup1 text null,
	contentGroup_previousContentGroup1 text null,
	contentGroup_previousContentGroup3 text null,
	contentGroup_contentGroup5 text null,
	contentGroup_contentGroup2 text null,
	contentGroup_contentGroupUniqueViews2 integer null,
	contentGroup_contentGroupUniqueViews1 integer null,
	contentGroup_contentGroupUniqueViews3 text null,
	contentGroup_previousContentGroup4 text null,
	contentGroup_contentGroup4 text null,
	contentGroup_previousContentGroup2 text null,
	contentGroup_previousContentGroup5 text null,
	eCommerceAction_option text null,
	eCommerceAction_action_type integer null,
	eCommerceAction_step integer null,
	eventInfo_eventAction text null,
	eventInfo_eventLabel text null,
	eventInfo_eventCategory text null,
	promotionActionInfo_promoIsClick text null,
	promotionActionInfo_promoIsView boolean null,
	social_hasSocialSourceReferral text null,
	social_socialInteractionNetworkAction text null,
	social_socialNetwork text null,
	transaction_localTransactionTax text null,
	transaction_transactionShipping text null,
	transaction_transactionCoupon text null,
	transaction_currencyCode text null,
	transaction_affiliation text null,
	transaction_transactionTax text null,
	transaction_localTransactionRevenue text null,
	transaction_localTransactionShipping text null,
	transaction_transactionId text null,
	transaction_transactionRevenue text null,
	item_currencyCode text null,
	item_transactionId text null
);

-- Copy data from .csv file to the table created above
copy google_merchandising.hits
from 'path\hits.csv'
with csv header;

-- Preview table
select * from google_merchandising.hits
limit 10;